// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// newcoeffn
SEXP newcoeffn(SEXP xstarin, SEXP Qin, SEXP ystarin);
RcppExport SEXP _rpql_newcoeffn(SEXP xstarinSEXP, SEXP QinSEXP, SEXP ystarinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xstarin(xstarinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Qin(QinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ystarin(ystarinSEXP);
    rcpp_result_gen = Rcpp::wrap(newcoeffn(xstarin, Qin, ystarin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rpql_newcoeffn", (DL_FUNC) &_rpql_newcoeffn, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rpql(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
